/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArticleIdRouteRouteImport } from './routes/article/$id/route'
import { Route as ArticleIdIndexRouteImport } from './routes/article/$id/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleIdRouteRoute = ArticleIdRouteRouteImport.update({
  id: '/article/$id',
  path: '/article/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleIdIndexRoute = ArticleIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArticleIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/article/$id': typeof ArticleIdRouteRouteWithChildren
  '/article/$id/': typeof ArticleIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/article/$id': typeof ArticleIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/article/$id': typeof ArticleIdRouteRouteWithChildren
  '/article/$id/': typeof ArticleIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/article/$id' | '/article/$id/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/article/$id'
  id: '__root__' | '/' | '/article/$id' | '/article/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArticleIdRouteRoute: typeof ArticleIdRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article/$id': {
      id: '/article/$id'
      path: '/article/$id'
      fullPath: '/article/$id'
      preLoaderRoute: typeof ArticleIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article/$id/': {
      id: '/article/$id/'
      path: '/'
      fullPath: '/article/$id/'
      preLoaderRoute: typeof ArticleIdIndexRouteImport
      parentRoute: typeof ArticleIdRouteRoute
    }
  }
}

interface ArticleIdRouteRouteChildren {
  ArticleIdIndexRoute: typeof ArticleIdIndexRoute
}

const ArticleIdRouteRouteChildren: ArticleIdRouteRouteChildren = {
  ArticleIdIndexRoute: ArticleIdIndexRoute,
}

const ArticleIdRouteRouteWithChildren = ArticleIdRouteRoute._addFileChildren(
  ArticleIdRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArticleIdRouteRoute: ArticleIdRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
